export const PROVIDER_IDS = ["douyin", "minimax", "elevenlabs", "luna", "qwen", "siliconflow"] as const

export type ProviderId = (typeof PROVIDER_IDS)[number]

export interface OptionItem {
  value: string
  label: string
}

export interface ProviderMeta {
  id: ProviderId
  label: string
  description: string
}

export const PROVIDERS: ProviderMeta[] = [
  { id: "luna", label: "LunaLabs", description: "LunaLabs TTS" },
  { id: "douyin", label: "豆包火山", description: "火山引擎TTS (含LLM和标准版本)" },
  { id: "minimax", label: "Minimax", description: "Minimax TTS" },
  { id: "elevenlabs", label: "ElevenLabs", description: "ElevenLabs TTS (暂不可用)" },
  { id: "qwen", label: "通义千问", description: "Qwen TTS" },
  { id: "siliconflow", label: "OpenMOSS", description: "SiliconFlow MOSS-TTSD 智能语音合成" },
]

export const PROVIDER_LABELS: Record<string, string> = PROVIDERS.reduce((acc, provider) => {
  acc[provider.id] = provider.label
  return acc
}, {} as Record<string, string>)

export const PROVIDER_MODELS: Record<ProviderId, OptionItem[]> = {
  // Douyin / Volcano TTS: 合并LLM和标准版本
  douyin: [
    { value: "volcano_llm", label: "DoubaoTTS2.0" },
    { value: "volcano_standard", label: "TTS(Standard) - 标准语音" },
  ],
  minimax: [
    { value: "speech-2.6-hd", label: "Speech 2.6 HD" },
    { value: "speech-2.6-turbo", label: "Speech 2.6 Turbo" },
    { value: "speech-2.5-hd-preview", label: "Speech 2.5 HD Preview" },
    { value: "speech-2.5-turbo-preview", label: "Speech 2.5 Turbo Preview" },
    { value: "speech-02-hd", label: "Speech 02 HD" },
    { value: "speech-02-turbo", label: "Speech 02 Turbo" },
    { value: "speech-01-hd", label: "Speech 01 HD" },
    { value: "speech-01-turbo", label: "Speech 01 Turbo" },
  ],
  elevenlabs: [
    { value: "eleven_v3", label: "V3" },
    { value: "eleven_multilingual_v2", label: "Multilingual V2" },
    { value: "eleven_turbo_v2_5", label: "Turbo V2.5" },
    { value: "eleven_turbo_v2", label: "Turbo V2" },
    { value: "eleven_flash_v2_5", label: "Flash V2.5" },
    { value: "eleven_flash_v2", label: "Flash V2" },
  ],
  luna: [
    { value: "lunalabs0", label: "LunaTTS0" },
    { value: "lunalabs1", label: "LunaTTS1" }
  ],
  qwen: [
    { value: "qwen3-tts-flash", label: "qwen3-tts-flash" },
  ],
  siliconflow: [
    { value: "fnlp/MOSS-TTSD-v0.5", label: "MOSS-TTSD v0.5" },
  ],
}

export const VOICE_OPTIONS: Record<ProviderId, OptionItem[]> = {
  douyin: [
    // === TTS(LLM) 智能语音音色 (推荐用于 volcano_llm 模型) ===
    { value: "zh_male_M392_conversation_wvae_bigtts", label: "男声-M392 (推荐)" },
    { value: "zh_female_vv_uranus_bigtts", label: "女声-Uranus" },
    { value: "zh_female_jingpin_wav", label: "女声-精品" },
    { value: "zh_female_tianmei_moon_tts", label: "女声-甜美" },
    { value: "zh_female_XiaoYun_tts", label: "女声-小云" },
    { value: "zh_male_jingpin_wav", label: "男声-精品" },
    { value: "zh_male_XiaoHu_tts", label: "男声-小虎" },
    { value: "zh_female_novel", label: "女声-小说" },
    { value: "zh_male_novel", label: "男声-小说" },

    // === TTS(Standard) 标准语音音色 (推荐用于 volcano_standard 模型) ===
    // 通用场景
    { value: "BV700_V2_streaming", label: "灿灿 2.0" },
    { value: "BV705_streaming", label: "炀炀" },
    { value: "BV701_V2_streaming", label: "擎苍 2.0" },
    { value: "BV001_V2_streaming", label: "通用女声 2.0" },
    { value: "BV700_streaming", label: "灿灿" },
    { value: "BV406_V2_streaming", label: "超自然音色-梓梓2.0" },
    { value: "BV406_streaming", label: "超自然音色-梓梓" },
    { value: "BV407_V2_streaming", label: "超自然音色-燃燃2.0" },
    { value: "BV407_streaming", label: "超自然音色-燃燃" },
    { value: "BV001_streaming", label: "通用女声" },
    { value: "BV002_streaming", label: "通用男声" },

    // 有声阅读
    { value: "BV701_streaming", label: "擎苍" },
    { value: "BV123_streaming", label: "阳光青年" },
    { value: "BV120_streaming", label: "反卷青年" },
    { value: "BV119_streaming", label: "通用赘婿" },
    { value: "BV115_streaming", label: "古风少御" },
    { value: "BV107_streaming", label: "霸气青叔" },
    { value: "BV100_streaming", label: "质朴青年" },
    { value: "BV104_streaming", label: "温柔淑女" },
    { value: "BV004_streaming", label: "开朗青年" },
    { value: "BV113_streaming", label: "甜宠少御" },
    { value: "BV102_streaming", label: "儒雅青年" },

    // 智能助手
    { value: "BV405_streaming", label: "甜美小源" },
    { value: "BV007_streaming", label: "亲切女声" },
    { value: "BV009_streaming", label: "知性女声" },
    { value: "BV419_streaming", label: "诚诚" },
    { value: "BV415_streaming", label: "童童" },
    { value: "BV008_streaming", label: "亲切男声" },

    // 视频配音
    { value: "BV408_streaming", label: "译制片男声" },
    { value: "BV426_streaming", label: "懒小羊" },
    { value: "BV428_streaming", label: "清新文艺女声" },
    { value: "BV403_streaming", label: "鸡汤女声" },
    { value: "BV158_streaming", label: "智慧老者" },
    { value: "BV157_streaming", label: "慈爱姥姥" },
    { value: "BR001_streaming", label: "说唱小哥" },
    { value: "BV410_streaming", label: "活力解说男" },
    { value: "BV411_streaming", label: "影视解说小帅" },
    { value: "BV437_streaming", label: "解说小帅-多情感" },
    { value: "BV412_streaming", label: "影视解说小美" },
    { value: "BV159_streaming", label: "纨绔青年" },
    { value: "BV418_streaming", label: "直播一姐" },
    { value: "BV142_streaming", label: "沉稳解说男" },
    { value: "BV143_streaming", label: "潇洒青年" },
    { value: "BV056_streaming", label: "阳光男声" },
    { value: "BV005_streaming", label: "活泼女声" },
    { value: "BV064_streaming", label: "小萝莉" },

    // 特色音色
    { value: "BV051_streaming", label: "奶气萌娃" },
    { value: "BV063_streaming", label: "动漫海绵" },
    { value: "BV417_streaming", label: "动漫海星" },
    { value: "BV050_streaming", label: "动漫小新" },
    { value: "BV061_streaming", label: "天才童声" },

    // 广告配音
    { value: "BV401_streaming", label: "促销男声" },
    { value: "BV402_streaming", label: "促销女声" },
    { value: "BV006_streaming", label: "磁性男声" },

    // 新闻播报
    { value: "BV011_streaming", label: "新闻女声" },
    { value: "BV012_streaming", label: "新闻男声" },

    // 教育场景
    { value: "BV034_streaming", label: "知性姐姐-双语" },
    { value: "BV033_streaming", label: "温柔小哥" },
  ],
  minimax: [
    { value: "male-qn-qingse", label: "青涩青年音色 (male-qn-qingse) — 中文" },
    { value: "male-qn-jingying", label: "精英青年音色 (male-qn-jingying) — 中文" },
    { value: "male-qn-badao", label: "霸道青年音色 (male-qn-badao) — 中文" },
    { value: "male-qn-daxuesheng", label: "青年大学生音色 (male-qn-daxuesheng) — 中文" },
    { value: "female-shaonv", label: "少女音色 (female-shaonv) — 中文" },
    { value: "female-yujie", label: "御姐音色 (female-yujie) — 中文" },
    { value: "female-chengshu", label: "成熟女性音色 (female-chengshu) — 中文" },
    { value: "female-tianmei", label: "甜美女性音色 (female-tianmei) — 中文" },
    { value: "presenter_male", label: "男性主持人 (presenter_male) — 中文" },
    { value: "presenter_female", label: "女性主持人 (presenter_female) — 中文" },
    { value: "audiobook_male_1", label: "男性有声书1 (audiobook_male_1) — 中文" },
    { value: "audiobook_male_2", label: "男性有声书2 (audiobook_male_2) — 中文" },
    { value: "audiobook_female_1", label: "女性有声书1 (audiobook_female_1) — 中文" },
    { value: "audiobook_female_2", label: "女性有声书2 (audiobook_female_2) — 中文" },
    { value: "male-qn-qingse-jingpin", label: "青涩青年音色-beta (male-qn-qingse-jingpin) — 中文" },
    { value: "male-qn-jingying-jingpin", label: "精英青年音色-beta (male-qn-jingying-jingpin) — 中文" },
    { value: "male-qn-badao-jingpin", label: "霸道青年音色-beta (male-qn-badao-jingpin) — 中文" },
    { value: "male-qn-daxuesheng-jingpin", label: "青年大学生音色-beta (male-qn-daxuesheng-jingpin) — 中文" },
    { value: "female-shaonv-jingpin", label: "少女音色-beta (female-shaonv-jingpin) — 中文" },
    { value: "female-yujie-jingpin", label: "御姐音色-beta (female-yujie-jingpin) — 中文" },
    { value: "female-chengshu-jingpin", label: "成熟女性音色-beta (female-chengshu-jingpin) — 中文" },
    { value: "female-tianmei-jingpin", label: "甜美女性音色-beta (female-tianmei-jingpin) — 中文" },
    { value: "clever_boy", label: "聪明男童 (clever_boy) — 中文" },
    { value: "cute_boy", label: "可爱男童 (cute_boy) — 中文" },
    { value: "lovely_girl", label: "萌萌女童 (lovely_girl) — 中文" },
    { value: "cartoon_pig", label: "卡通猪小琪 (cartoon_pig) — 中文" },
    { value: "bingjiao_didi", label: "病娇弟弟 (bingjiao_didi) — 中文" },
    { value: "junlang_nanyou", label: "俊朗男友 (junlang_nanyou) — 中文" },
    { value: "chunzhen_xuedi", label: "纯真学弟 (chunzhen_xuedi) — 中文" },
    { value: "lengdan_xiongzhang", label: "冷淡学长 (lengdan_xiongzhang) — 中文" },
    { value: "badao_shaoye", label: "霸道少爷 (badao_shaoye) — 中文" },
    { value: "tianxin_xiaoling", label: "甜心小玲 (tianxin_xiaoling) — 中文" },
    { value: "qiaopi_mengmei", label: "俏皮萌妹 (qiaopi_mengmei) — 中文" },
    { value: "wumei_yujie", label: "妩媚御姐 (wumei_yujie) — 中文" },
    { value: "diadia_xuemei", label: "嗲嗲学妹 (diadia_xuemei) — 中文" },
    { value: "danya_xuejie", label: "淡雅学姐 (danya_xuejie) — 中文" },
    { value: "Santa_Claus", label: "Santa Claus (Santa_Claus) — English" },
    { value: "Grinch", label: "Grinch (Grinch) — English" },
    { value: "Rudolph", label: "Rudolph (Rudolph) — English" },
    { value: "Arnold", label: "Arnold (Arnold) — English" },
    { value: "Charming_Santa", label: "Charming Santa (Charming_Santa) — English" },
    { value: "Charming_Lady", label: "Charming Lady (Charming_Lady) — English" },
    { value: "Sweet_Girl", label: "Sweet Girl (Sweet_Girl) — English" },
    { value: "Cute_Elf", label: "Cute Elf (Cute_Elf) — English" },
    { value: "Attractive_Girl", label: "Attractive Girl (Attractive_Girl) — English" },
    { value: "Serene_Woman", label: "Serene Woman (Serene_Woman) — English" },
  ],
  luna: [
    // LunaTTS0 音色 (formerly LunaTTS1)
    { value: "female", label: "Female" },
    { value: "male", label: "Male" },
    { value: "child", label: "Child" },
    { value: "youngmale", label: "Young Male" },
    { value: "youngfemale", label: "Young Female" },
    // LunaTTS1 音色 (formerly LunaTTS2) - 中文
    { value: "jingcheng", label: "播客景澄 (温和男青年)" },
    { value: "bochuan", label: "柏川FM (开朗男青年)" },
    { value: "zhining", label: "播客芷宁 (知性女青年)" },
    { value: "nianan", label: "念安FM (活泼女青年)" },
    { value: "jingyuan", label: "靖哥说书 (慵懒霸总)" },
    { value: "lixing", label: "有声的砺行 (温润中年男)" },
    { value: "jinyu", label: "有声的瑾瑜 (成熟温柔女声)" },
    { value: "qiyan", label: "绮言说书 (女青年)" },
    { value: "xiuyuan", label: "客服小远 (耐心男青年)" },
    { value: "zhixia", label: "客服小夏 (耐心女青年)" },
    { value: "xinxin", label: "新新同学 (俏皮童声)" },
    { value: "wukong", label: "孙悟空 (古灵精怪)" },
    { value: "bajie", label: "猪八戒 (憨厚喜感)" },
    { value: "linzi", label: "东北琳子 (直爽东北老妹)" },
    { value: "liuge", label: "广西柳哥 (搞笑广西表哥)" },
    { value: "qinyao", label: "沁瑶 (知心姐姐)" },
    { value: "xiyue", label: "曦月 (傲娇女友)" },
    { value: "ruoxi", label: "若兮 (粘人小妹妹)" },
    { value: "bochen", label: "柏辰 (温柔男友)" },
    // LunaTTS1 音色 (formerly LunaTTS2) - 英文
    { value: "michael", label: "Michael (美国男青年)" },
    { value: "james", label: "James (优雅英音男)" },
    { value: "grace", label: "Grace (优雅英音女)" },
    { value: "avery", label: "Avery (温和美国女青年)" },
    { value: "oscar", label: "Oscar (亲切美国男青年)" },
    { value: "olivia", label: "Olivia (亲切美国女青年)" },
    { value: "daniel", label: "Daniel (活力美国男青年)" },
    { value: "ella", label: "Ella (活力美国女青年)" },
    { value: "daisy", label: "Daisy (甜美温柔女友)" },
    { value: "fiona", label: "Fiona (细腻温柔女友)" },
    { value: "capriana", label: "Capriana (冷静理性女青年)" },
  ],
  qwen: [
    { value: "Cherry", label: "芊悦 — Cherry" },
    { value: "Ethan", label: "晨煦 — Ethan" },
    { value: "Nofish", label: "不吃鱼 — Nofish" },
    { value: "Jennifer", label: "詹妮弗 — Jennifer" },
    { value: "Ryan", label: "甜茶 — Ryan" },
    { value: "Katerina", label: "卡捷琳娜 — Katerina" },
    { value: "Elias", label: "墨讲师 — Elias" },
    { value: "Jada", label: "上海-阿珍 — Jada" },
    { value: "Dylan", label: "北京-晓东 — Dylan" },
    { value: "Sunny", label: "四川-晴儿 — Sunny" },
    { value: "li", label: "南京-老李 — li" },
    { value: "Marcus", label: "陕西-秦川 — Marcus" },
    { value: "Roy", label: "闽南-阿杰 — Roy" },
    { value: "Peter", label: "天津-李彼得 — Peter" },
    { value: "Rocky", label: "粤语-阿强 — Rocky" },
    { value: "Kiki", label: "粤语-阿清 — Kiki" },
    { value: "Eric", label: "四川-程川 — Eric" },
  ],
  elevenlabs: [
    { value: "21m00Tcm4TlvDq8ikWAM", label: "Rachel — EN" },
    { value: "29vD33N1CtxCmqQRPOHJ", label: "Drew — EN" },
    { value: "2EiwWnXFnvU5JabPnv8n", label: "Clyde — EN" },
    { value: "5Q0t7uMcjvnagumLfvZi", label: "Paul — EN" },
    { value: "9BWtsMINqrJLrRacOk9x", label: "Aria — EN / FR / ZH / TR" },
    { value: "AZnzlk1XvdvUeBnXmlld", label: "Domi" },
    { value: "CYw3kZ02Hs0563khs1Fj", label: "Dave — EN" },
    { value: "CwhRBWXzGAHq8TQ4Fs17", label: "Roger — EN / FR / DE / NL / ES" },
    { value: "D38z5RcWu1voky8WS1ja", label: "Fin — EN" },
    { value: "EXAVITQu4vr4xnSDxMaL", label: "Sarah — EN / FR / AR / ZH / ES / HI" },
  ],
  siliconflow: [
    { value: "alex", label: "Alex (男声)" },
    { value: "anna", label: "Anna (女声)" },
    { value: "bella", label: "Bella (女声)" },
    { value: "benjamin", label: "Benjamin (男声)" },
    { value: "charles", label: "Charles (男声)" },
    { value: "claire", label: "Claire (女声)" },
    { value: "david", label: "David (男声)" },
    { value: "diana", label: "Diana (女声)" },
  ],
}

export const DOUYIN_LLM_VOICE_OPTIONS: OptionItem[] = [
  // 通用场景
  { value: "zh_female_vv_uranus_bigtts", label: "vivi" },

  // 多情感
  { value: "zh_male_lengkugege_emo_v2_mars_bigtts", label: "冷酷哥哥（多情感）" },
  { value: "zh_female_tianxinxiaomei_emo_v2_mars_bigtts", label: "甜心小美（多情感）" },
  { value: "zh_female_gaolengyujie_emo_v2_mars_bigtts", label: "高冷御姐（多情感）" },
  { value: "zh_male_aojiaobazong_emo_v2_mars_bigtts", label: "傲娇霸总（多情感）" },
  { value: "zh_male_guangzhoudege_emo_mars_bigtts", label: "广州德哥（多情感）" },
  { value: "zh_male_jingqiangkanye_emo_mars_bigtts", label: "京腔侃爷（多情感）" },
  { value: "zh_female_linjuayi_emo_v2_mars_bigtts", label: "邻居阿姨（多情感）" },
  { value: "zh_male_yourougongzi_emo_v2_mars_bigtts", label: "优柔公子（多情感）" },
  { value: "zh_male_ruyayichen_emo_v2_mars_bigtts", label: "儒雅男友（多情感）" },
  { value: "zh_male_junlangnanyou_emo_v2_mars_bigtts", label: "俊朗男友（多情感）" },
  { value: "zh_male_beijingxiaoye_emo_v2_mars_bigtts", label: "北京小爷（多情感）" },
  { value: "zh_female_roumeinvyou_emo_v2_mars_bigtts", label: "柔美女友（多情感）" },
  { value: "zh_male_yangguangqingnian_emo_v2_mars_bigtts", label: "阳光青年（多情感）" },
  { value: "zh_female_meilinvyou_emo_v2_mars_bigtts", label: "魅力女友（多情感）" },
  { value: "zh_female_shuangkuaisisi_emo_v2_mars_bigtts", label: "爽快思思（多情感）" },

  // 英文多情感
  { value: "en_female_candice_emo_v2_mars_bigtts", label: "Candice" },
  { value: "en_female_skye_emo_v2_mars_bigtts", label: "Serena" },
  { value: "en_male_glen_emo_v2_mars_bigtts", label: "Glen" },
  { value: "en_male_sylus_emo_v2_mars_bigtts", label: "Sylus" },
  { value: "en_male_corey_emo_v2_mars_bigtts", label: "Corey" },
  { value: "en_female_nadia_tips_emo_v2_mars_bigtts", label: "Nadia" },

  // 教育场景
  { value: "zh_female_yingyujiaoyu_mars_bigtts", label: "Tina老师" },

  // 通用场景
  { value: "ICL_zh_female_wenrounvshen_239eff5e8ffa_tob", label: "温柔女神" },
  { value: "zh_female_vv_mars_bigtts", label: "Vivi" },
  { value: "zh_female_qinqienvsheng_moon_bigtts", label: "亲切女声" },
  { value: "ICL_zh_male_shenmi_v1_tob", label: "机灵小伙" },
  { value: "ICL_zh_female_wuxi_tob", label: "元气甜妹" },
  { value: "ICL_zh_female_wenyinvsheng_v1_tob", label: "知心姐姐" },
  { value: "zh_male_qingyiyuxuan_mars_bigtts", label: "阳光阿辰" },
  { value: "zh_male_xudong_conversation_wvae_bigtts", label: "快乐小东" },
  { value: "ICL_zh_male_lengkugege_v1_tob", label: "冷酷哥哥" },
  { value: "ICL_zh_female_feicui_v1_tob", label: "纯澈女生" },
  { value: "ICL_zh_female_yuxin_v1_tob", label: "初恋女友" },
  { value: "ICL_zh_female_xnx_tob", label: "贴心闺蜜" },
  { value: "ICL_zh_female_yry_tob", label: "温柔白月光" },
  { value: "en_male_jason_conversation_wvae_bigtts", label: "开朗学长" },
  { value: "zh_female_sophie_conversation_wvae_bigtts", label: "魅力苏菲" },
  { value: "ICL_zh_female_yilin_tob", label: "贴心妹妹" },
  { value: "zh_female_tianmeitaozi_mars_bigtts", label: "甜美桃子" },
  { value: "zh_female_qingxinnvsheng_mars_bigtts", label: "清新女声" },
  { value: "zh_female_zhixingnvsheng_mars_bigtts", label: "知性女声" },
  { value: "zh_male_qingshuangnanda_mars_bigtts", label: "清爽男大" },
  { value: "zh_female_linjianvhai_moon_bigtts", label: "邻家女孩" },
  { value: "zh_male_yuanboxiaoshu_moon_bigtts", label: "渊博小叔" },
  { value: "zh_male_yangguangqingnian_moon_bigtts", label: "阳光青年" },
  { value: "zh_female_tianmeixiaoyuan_moon_bigtts", label: "甜美小源" },
  { value: "zh_female_qingchezizi_moon_bigtts", label: "清澈梓梓" },
  { value: "zh_male_jieshuoxiaoming_moon_bigtts", label: "解说小明" },
  { value: "zh_female_kailangjiejie_moon_bigtts", label: "开朗姐姐" },
  { value: "zh_male_linjiananhai_moon_bigtts", label: "邻家男孩" },
  { value: "zh_female_tianmeiyueyue_moon_bigtts", label: "甜美悦悦" },
  { value: "zh_female_xinlingjitang_moon_bigtts", label: "心灵鸡汤" },
  { value: "ICL_zh_female_zhixingwenwan_tob", label: "知性温婉" },
  { value: "ICL_zh_male_nuanxintitie_tob", label: "暖心体贴" },
  { value: "ICL_zh_male_kailangqingkuai_tob", label: "开朗轻快" },
  { value: "ICL_zh_male_huoposhuanglang_tob", label: "活泼爽朗" },
  { value: "ICL_zh_male_shuaizhenxiaohuo_tob", label: "率真小伙" },
  { value: "zh_male_wenrouxiaoge_mars_bigtts", label: "温柔小哥" },
  { value: "zh_female_cancan_mars_bigtts", label: "灿灿/Shiny" },
  { value: "zh_female_shuangkuaisisi_moon_bigtts", label: "爽快思思/Skye" },
  { value: "zh_male_wennuanahu_moon_bigtts", label: "温暖阿虎/Alvin" },
  { value: "zh_male_shaonianzixin_moon_bigtts", label: "少年梓辛/Brayan" },

  // 通用场景、S2S-SC
  { value: "ICL_zh_female_wenrouwenya_tob", label: "温柔文雅" },

  // 趣味口音
  { value: "zh_male_hupunan_mars_bigtts", label: "沪普男" },
  { value: "zh_male_lubanqihao_mars_bigtts", label: "鲁班七号" },
  { value: "zh_female_yangmi_mars_bigtts", label: "林潇" },
  { value: "zh_female_linzhiling_mars_bigtts", label: "玲玲姐姐" },
  { value: "zh_female_jiyejizi2_mars_bigtts", label: "春日部姐姐" },
  { value: "zh_male_tangseng_mars_bigtts", label: "唐僧" },
  { value: "zh_male_zhuangzhou_mars_bigtts", label: "庄周" },
  { value: "zh_male_zhubajie_mars_bigtts", label: "猪八戒" },
  { value: "zh_female_ganmaodianyin_mars_bigtts", label: "感冒电音姐姐" },
  { value: "zh_female_naying_mars_bigtts", label: "直率英子" },
  { value: "zh_female_leidian_mars_bigtts", label: "女雷神" },
  { value: "zh_male_yuzhouzixuan_moon_bigtts", label: "豫州子轩" },
  { value: "zh_female_daimengchuanmei_moon_bigtts", label: "呆萌川妹" },
  { value: "zh_male_guangxiyuanzhou_moon_bigtts", label: "广西远舟" },
  { value: "zh_male_zhoujielun_emo_v2_mars_bigtts", label: "双节棍小哥" },
  { value: "zh_female_wanwanxiaohe_moon_bigtts", label: "湾湾小何" },
  { value: "zh_female_wanqudashu_moon_bigtts", label: "湾区大叔" },
  { value: "zh_male_guozhoudege_moon_bigtts", label: "广州德哥" },
  { value: "zh_male_haoyuxiaoge_moon_bigtts", label: "浩宇小哥" },
  { value: "zh_male_beijingxiaoye_moon_bigtts", label: "北京小爷" },
  { value: "zh_male_jingqiangkanye_moon_bigtts", label: "京腔侃爷/Harmony" },
  { value: "zh_female_meituojieer_moon_bigtts", label: "妹坨洁儿" },

  // 角色扮演
  { value: "ICL_zh_female_chunzhenshaonv_e588402fb8ad_tob", label: "纯真少女" },
  { value: "ICL_zh_male_xiaonaigou_edf58cf28b8b_tob", label: "奶气小生" },
  { value: "ICL_zh_female_jinglingxiangdao_1beb294a9e3e_tob", label: "精灵向导" },
  { value: "ICL_zh_male_menyoupingxiaoge_ffed9fc2fee7_tob", label: "闷油瓶小哥" },
  { value: "ICL_zh_male_anrenqinzhu_cd62e63dcdab_tob", label: "黯刃秦主" },
  { value: "ICL_zh_male_badaozongcai_v1_tob", label: "霸道总裁" },
  { value: "ICL_zh_female_ganli_v1_tob", label: "妩媚可人" },
  { value: "ICL_zh_female_xiangliangya_v1_tob", label: "邪魅御姐" },
  { value: "ICL_zh_male_ms_tob", label: "嚣张小哥" },
  { value: "ICL_zh_male_you_tob", label: "油腻大叔" },
  { value: "ICL_zh_male_guaogongzi_v1_tob", label: "孤傲公子" },
  { value: "ICL_zh_male_huzi_v1_tob", label: "胡子叔叔" },
  { value: "ICL_zh_female_luoqing_v1_tob", label: "性感魅惑" },
  { value: "ICL_zh_male_bingruogongzi_tob", label: "病弱公子" },
  { value: "ICL_zh_female_bingjiao3_tob", label: "邪魅女王" },
  { value: "ICL_zh_male_aomanqingnian_tob", label: "傲慢青年" },
  { value: "ICL_zh_male_cujingnansheng_tob", label: "醋精男生" },
  { value: "ICL_zh_male_shuanglangshaonian_tob", label: "爽朗少年" },
  { value: "ICL_zh_male_sajiaonanyou_tob", label: "撒娇男友" },
  { value: "ICL_zh_male_wenrounanyou_tob", label: "温柔男友" },
  { value: "ICL_zh_male_wenshunshaonian_tob", label: "温顺少年" },
  { value: "ICL_zh_male_naigounanyou_tob", label: "粘人男友" },
  { value: "ICL_zh_male_sajiaonansheng_tob", label: "撒娇男生" },
  { value: "ICL_zh_male_huoponanyou_tob", label: "活泼男友" },
  { value: "ICL_zh_male_tianxinanyou_tob", label: "甜系男友" },
  { value: "ICL_zh_male_huoliqingnian_tob", label: "活力青年" },
  { value: "ICL_zh_male_kailangqingnian_tob", label: "开朗青年" },
  { value: "ICL_zh_male_lengmoxiongzhang_tob", label: "冷漠兄长" },
  { value: "ICL_zh_male_tiancaitongzhuo_tob", label: "天才同桌" },
  { value: "ICL_zh_male_pianpiangongzi_tob", label: "翩翩公子" },
  { value: "ICL_zh_male_mengdongqingnian_tob", label: "懵懂青年" },
  { value: "ICL_zh_male_lenglianxiongzhang_tob", label: "冷脸兄长" },
  { value: "ICL_zh_male_bingjiaoshaonian_tob", label: "病娇少年" },
  { value: "ICL_zh_male_bingjiaonanyou_tob", label: "病娇男友" },
  { value: "ICL_zh_male_bingruoshaonian_tob", label: "病弱少年" },
  { value: "ICL_zh_male_yiqishaonian_tob", label: "意气少年" },
  { value: "ICL_zh_male_ganjingshaonian_tob", label: "干净少年" },
  { value: "ICL_zh_male_lengmonanyou_tob", label: "冷漠男友" },
  { value: "ICL_zh_male_jingyingqingnian_tob", label: "精英青年" },
  { value: "ICL_zh_male_rexueshaonian_tob", label: "热血少年" },
  { value: "ICL_zh_male_qingshuangshaonian_tob", label: "清爽少年" },
  { value: "ICL_zh_male_zhongerqingnian_tob", label: "中二青年" },
  { value: "ICL_zh_male_lingyunqingnian_tob", label: "凌云青年" },
  { value: "ICL_zh_male_zifuqingnian_tob", label: "自负青年" },
  { value: "ICL_zh_male_bujiqingnian_tob", label: "不羁青年" },
  { value: "ICL_zh_male_ruyajunzi_tob", label: "儒雅君子" },
  { value: "ICL_zh_male_diyinchenyu_tob", label: "低音沉郁" },
  { value: "ICL_zh_male_lenglianxueba_tob", label: "冷脸学霸" },
  { value: "ICL_zh_male_ruyazongcai_tob", label: "儒雅总裁" },
  { value: "ICL_zh_male_shenchenzongcai_tob", label: "深沉总裁" },
  { value: "ICL_zh_male_xiaohouye_tob", label: "小侯爷" },
  { value: "ICL_zh_male_gugaogongzi_tob", label: "孤高公子" },
  { value: "ICL_zh_male_zhangjianjunzi_tob", label: "仗剑君子" },
  { value: "ICL_zh_male_wenrunxuezhe_tob", label: "温润学者" },
  { value: "ICL_zh_male_qinqieqingnian_tob", label: "亲切青年" },
  { value: "ICL_zh_male_wenrouxuezhang_tob", label: "温柔学长" },
  { value: "ICL_zh_male_gaolengzongcai_tob", label: "高冷总裁" },
  { value: "ICL_zh_male_lengjungaozhi_tob", label: "冷峻高智" },
  { value: "ICL_zh_male_chanruoshaoye_tob", label: "孱弱少爷" },
  { value: "ICL_zh_male_zixinqingnian_tob", label: "自信青年" },
  { value: "ICL_zh_male_qingseqingnian_tob", label: "青涩青年" },
  { value: "ICL_zh_male_xuebatongzhuo_tob", label: "学霸同桌" },
  { value: "ICL_zh_male_lengaozongcai_tob", label: "冷傲总裁" },
  { value: "ICL_zh_male_yuanqishaonian_tob", label: "元气少年" },
  { value: "ICL_zh_male_satuoqingnian_tob", label: "洒脱青年" },
  { value: "ICL_zh_male_zhishuaiqingnian_tob", label: "直率青年" },
  { value: "ICL_zh_male_siwenqingnian_tob", label: "斯文青年" },
  { value: "ICL_zh_male_junyigongzi_tob", label: "俊逸公子" },
  { value: "ICL_zh_male_zhangjianxiake_tob", label: "仗剑侠客" },
  { value: "ICL_zh_male_jijiaozhineng_tob", label: "机甲智能" },
  { value: "zh_male_naiqimengwa_mars_bigtts", label: "奶气萌娃" },
  { value: "zh_female_popo_mars_bigtts", label: "婆婆" },
  { value: "zh_female_gaolengyujie_moon_bigtts", label: "高冷御姐" },
  { value: "zh_male_aojiaobazong_moon_bigtts", label: "傲娇霸总" },
  { value: "zh_female_meilinvyou_moon_bigtts", label: "魅力女友" },
  { value: "zh_male_shenyeboke_moon_bigtts", label: "深夜播客" },
  { value: "zh_female_sajiaonvyou_moon_bigtts", label: "柔美女友" },
  { value: "zh_female_yuanqinvyou_moon_bigtts", label: "撒娇学妹" },
  { value: "ICL_zh_female_bingruoshaonv_tob", label: "病弱少女" },
  { value: "ICL_zh_female_huoponvhai_tob", label: "活泼女孩" },
  { value: "zh_male_dongfanghaoran_moon_bigtts", label: "东方浩然" },
  { value: "ICL_zh_male_lvchaxiaoge_tob", label: "绿茶小哥" },
  { value: "ICL_zh_female_jiaoruoluoli_tob", label: "娇弱萝莉" },
  { value: "ICL_zh_male_lengdanshuli_tob", label: "冷淡疏离" },
  { value: "ICL_zh_male_hanhoudunshi_tob", label: "憨厚敦实" },
  { value: "ICL_zh_female_huopodiaoman_tob", label: "活泼刁蛮" },
  { value: "ICL_zh_male_guzhibingjiao_tob", label: "固执病娇" },
  { value: "ICL_zh_male_sajiaonianren_tob", label: "撒娇粘人" },
  { value: "ICL_zh_female_aomanjiaosheng_tob", label: "傲慢娇声" },
  { value: "ICL_zh_male_xiaosasuixing_tob", label: "潇洒随性" },
  { value: "ICL_zh_male_guiyishenmi_tob", label: "诡异神秘" },
  { value: "ICL_zh_male_ruyacaijun_tob", label: "儒雅才俊" },
  { value: "ICL_zh_male_zhengzhiqingnian_tob", label: "正直青年" },
  { value: "ICL_zh_female_jiaohannvwang_tob", label: "娇憨女王" },
  { value: "ICL_zh_female_bingjiaomengmei_tob", label: "病娇萌妹" },
  { value: "ICL_zh_male_qingsenaigou_tob", label: "青涩小生" },
  { value: "ICL_zh_male_chunzhenxuedi_tob", label: "纯真学弟" },
  { value: "ICL_zh_male_youroubangzhu_tob", label: "优柔帮主" },
  { value: "ICL_zh_male_yourougongzi_tob", label: "优柔公子" },
  { value: "ICL_zh_female_tiaopigongzhu_tob", label: "调皮公主" },
  { value: "ICL_zh_male_tiexinnanyou_tob", label: "贴心男友" },
  { value: "ICL_zh_male_shaonianjiangjun_tob", label: "少年将军" },
  { value: "ICL_zh_male_bingjiaogege_tob", label: "病娇哥哥" },
  { value: "ICL_zh_male_xuebanantongzhuo_tob", label: "学霸男同桌" },
  { value: "ICL_zh_male_youmoshushu_tob", label: "幽默叔叔" },
  { value: "ICL_zh_female_jiaxiaozi_tob", label: "假小子" },
  { value: "ICL_zh_male_wenrounantongzhuo_tob", label: "温柔男同桌" },
  { value: "ICL_zh_male_youmodaye_tob", label: "幽默大爷" },
  { value: "ICL_zh_male_asmryexiu_tob", label: "枕边低语" },
  { value: "ICL_zh_male_shenmifashi_tob", label: "神秘法师" },
  { value: "zh_female_jiaochuan_mars_bigtts", label: "娇喘女声" },
  { value: "zh_male_livelybro_mars_bigtts", label: "开朗弟弟" },
  { value: "zh_female_flattery_mars_bigtts", label: "谄媚女声" },
  { value: "ICL_zh_male_lengjunshangsi_tob", label: "冷峻上司" },

  // 角色扮演、S2S-SC
  { value: "ICL_zh_male_cujingnanyou_tob", label: "醋精男友" },
  { value: "ICL_zh_male_fengfashaonian_tob", label: "风发少年" },
  { value: "ICL_zh_male_cixingnansang_tob", label: "磁性男嗓" },
  { value: "ICL_zh_male_chengshuzongcai_tob", label: "成熟总裁" },
  { value: "ICL_zh_male_aojiaojingying_tob", label: "傲娇精英" },
  { value: "ICL_zh_male_aojiaogongzi_tob", label: "傲娇公子" },
  { value: "ICL_zh_male_badaoshaoye_tob", label: "霸道少爷" },
  { value: "ICL_zh_male_fuheigongzi_tob", label: "腹黑公子" },
  { value: "ICL_zh_female_nuanxinxuejie_tob", label: "暖心学姐" },
  { value: "ICL_zh_female_keainvsheng_tob", label: "可爱女生" },
  { value: "ICL_zh_female_chengshujiejie_tob", label: "成熟姐姐" },
  { value: "ICL_zh_female_bingjiaojiejie_tob", label: "病娇姐姐" },
  { value: "ICL_zh_female_wumeiyujie_tob", label: "妩媚御姐" },
  { value: "ICL_zh_female_aojiaonvyou_tob", label: "傲娇女友" },
  { value: "ICL_zh_female_tiexinnvyou_tob", label: "贴心女友" },
  { value: "ICL_zh_female_xingganyujie_tob", label: "性感御姐" },
  { value: "ICL_zh_male_bingjiaodidi_tob", label: "病娇弟弟" },
  { value: "ICL_zh_male_aomanshaoye_tob", label: "傲慢少爷" },
  { value: "ICL_zh_male_aiqilingren_tob", label: "傲气凌人" },
  { value: "ICL_zh_male_bingjiaobailian_tob", label: "病娇白莲" },

  // 多语种
  { value: "en_female_lauren_moon_bigtts", label: "Lauren" },
  { value: "en_male_campaign_jamal_moon_bigtts", label: "Energetic Male II" },
  { value: "en_male_chris_moon_bigtts", label: "Gotham Hero" },
  { value: "en_female_product_darcie_moon_bigtts", label: "Flirty Female" },
  { value: "en_female_emotional_moon_bigtts", label: "Peaceful Female" },
  { value: "en_female_nara_moon_bigtts", label: "Nara" },
  { value: "en_male_bruce_moon_bigtts", label: "Bruce" },
  { value: "en_male_michael_moon_bigtts", label: "Michael" },
  { value: "ICL_en_male_cc_sha_v1_tob", label: "Cartoon Chef" },
  { value: "zh_male_M100_conversation_wvae_bigtts", label: "Lucas" },
  { value: "zh_female_sophie_conversation_wvae_bigtts", label: "Sophie" },
  { value: "en_female_dacey_conversation_wvae_bigtts", label: "Daisy" },
  { value: "en_male_charlie_conversation_wvae_bigtts", label: "Owen" },
  { value: "en_female_sarah_new_conversation_wvae_bigtts", label: "Luna" },
  { value: "ICL_en_male_michael_tob", label: "Michael" },
  { value: "ICL_en_female_cc_cm_v1_tob", label: "Charlie" },
  { value: "ICL_en_male_oogie2_tob", label: "Big Boogie" },
  { value: "ICL_en_male_frosty1_tob", label: "Frosty Man" },
  { value: "ICL_en_male_grinch2_tob", label: "The Grinch" },
  { value: "ICL_en_male_zayne_tob", label: "Zayne" },
  { value: "ICL_en_male_cc_jigsaw_tob", label: "Jigsaw" },
  { value: "ICL_en_male_cc_chucky_tob", label: "Chucky" },
  { value: "ICL_en_male_cc_penny_v1_tob", label: "Clown Man" },
  { value: "ICL_en_male_kevin2_tob", label: "Kevin McCallister" },
  { value: "ICL_en_male_xavier1_v1_tob", label: "Xavier" },
  { value: "ICL_en_male_cc_dracula_v1_tob", label: "Noah" },
  { value: "en_male_adam_mars_bigtts", label: "Adam" },
  { value: "en_female_amanda_mars_bigtts", label: "Amanda" },
  { value: "en_male_jackson_mars_bigtts", label: "Jackson" },
  { value: "en_female_daisy_moon_bigtts", label: "Delicate Girl" },
  { value: "en_male_dave_moon_bigtts", label: "Dave" },
  { value: "en_male_hades_moon_bigtts", label: "Hades" },
  { value: "en_female_onez_moon_bigtts", label: "Onez" },
  { value: "en_female_emily_mars_bigtts", label: "Emily" },
  { value: "zh_male_xudong_conversation_wvae_bigtts", label: "Daniel" },
  { value: "ICL_en_male_cc_alastor_tob", label: "Alastor" },
  { value: "en_male_smith_mars_bigtts", label: "Smith" },
  { value: "en_female_anna_mars_bigtts", label: "Anna" },
  { value: "ICL_en_male_aussie_v1_tob", label: "Ethan" },
  { value: "en_female_sarah_mars_bigtts", label: "Sarah" },
  { value: "en_male_dryw_mars_bigtts", label: "Dryw" },
  { value: "multi_female_maomao_conversation_wvae_bigtts", label: "Diana" },
  { value: "multi_male_M100_conversation_wvae_bigtts", label: "Lucía" },
  { value: "multi_female_sophie_conversation_wvae_bigtts", label: "Sofía" },
  { value: "multi_male_xudong_conversation_wvae_bigtts", label: "Daníel" },
  { value: "multi_zh_male_youyoujunzi_moon_bigtts", label: "ひかる（光）" },
  { value: "multi_female_sophie_conversation_wvae_bigtts", label: "さとみ（智美）" },
  { value: "multi_male_xudong_conversation_wvae_bigtts", label: "まさお（正男）" },
  { value: "multi_female_maomao_conversation_wvae_bigtts", label: "つき（月）" },
  { value: "multi_female_gaolengyujie_moon_bigtts", label: "あけみ（朱美）" },
  { value: "multi_male_jingqiangkanye_moon_bigtts", label: "かずね（和音）/Javier or Álvaro" },
  { value: "multi_female_shuangkuaisisi_moon_bigtts", label: "はるこ（晴子）/Esmeralda" },
  { value: "multi_male_wanqudashu_moon_bigtts", label: "ひろし（広志）/Roberto" },

  // 客服场景
  { value: "ICL_zh_female_lixingyuanzi_cs", label: "理性圆子" },
  { value: "ICL_zh_female_qingtiantaotao_cs", label: "清甜桃桃" },
  { value: "ICL_zh_female_qingxixiaoxue_cs", label: "清晰小雪" },
  { value: "ICL_zh_female_qingtianmeimei_cs", label: "清甜莓莓" },
  { value: "ICL_zh_female_kailangtingting_cs", label: "开朗婷婷" },
  { value: "ICL_zh_male_qingxinmumu_cs", label: "清新沐沐" },
  { value: "ICL_zh_male_shuanglangxiaoyang_cs", label: "爽朗小阳" },
  { value: "ICL_zh_male_qingxinbobo_cs", label: "清新波波" },
  { value: "ICL_zh_female_wenwanshanshan_cs", label: "温婉珊珊" },
  { value: "ICL_zh_female_tianmeixiaoyu_cs_tob", label: "甜美小雨" },
  { value: "ICL_zh_female_reqingaina_cs_tob", label: "热情艾娜" },
  { value: "ICL_zh_female_tianmeixiaoju_cs_tob", label: "甜美小橘" },
  { value: "ICL_zh_male_chenwenmingzai_cs_tob", label: "沉稳明仔" },
  { value: "ICL_zh_male_qinqiexiaozhuo_cs_tob", label: "亲切小卓" },
  { value: "ICL_zh_female_lingdongxinxin_cs_tob", label: "灵动欣欣" },
  { value: "ICL_zh_female_guaiqiaokeer_cs_tob", label: "乖巧可儿" },
  { value: "ICL_zh_female_nuanxinqianqian_cs_tob", label: "暖心茜茜" },
  { value: "ICL_zh_female_ruanmengtuanzi_cs_tob", label: "软萌团子" },
  { value: "ICL_zh_male_yangguangyangyang_cs_tob", label: "阳光洋洋" },
  { value: "ICL_zh_female_ruanmengtangtang_cs_tob", label: "软萌糖糖" },
  { value: "ICL_zh_female_xiuliqianqian_cs_tob", label: "秀丽倩倩" },
  { value: "ICL_zh_female_kaixinxiaohong_cs_tob", label: "开心小鸿" },
  { value: "ICL_zh_female_qingyingduoduo_cs_tob", label: "轻盈朵朵" },
  { value: "zh_female_kefunvsheng_mars_bigtts", label: "暖阳女声" },

  // 视频配音
  { value: "zh_male_M100_conversation_wvae_bigtts", label: "悠悠君子" },
  { value: "zh_female_maomao_conversation_wvae_bigtts", label: "文静毛毛" },
  { value: "ICL_zh_female_qiuling_v1_tob", label: "倾心少女" },
  { value: "ICL_zh_male_buyan_v1_tob", label: "醇厚低音" },
  { value: "ICL_zh_male_BV144_paoxiaoge_v1_tob", label: "咆哮小哥" },
  { value: "ICL_zh_female_heainainai_tob", label: "和蔼奶奶" },
  { value: "ICL_zh_female_linjuayi_tob", label: "邻居阿姨" },
  { value: "zh_female_wenrouxiaoya_moon_bigtts", label: "温柔小雅" },
  { value: "zh_male_tiancaitongsheng_mars_bigtts", label: "天才童声" },
  { value: "zh_male_sunwukong_mars_bigtts", label: "猴哥" },
  { value: "zh_male_xionger_mars_bigtts", label: "熊二" },
  { value: "zh_female_peiqi_mars_bigtts", label: "佩奇猪" },
  { value: "zh_female_wuzetian_mars_bigtts", label: "武则天" },
  { value: "zh_female_gujie_mars_bigtts", label: "顾姐" },
  { value: "zh_female_yingtaowanzi_mars_bigtts", label: "樱桃丸子" },
  { value: "zh_male_chunhui_mars_bigtts", label: "广告解说" },
  { value: "zh_female_shaoergushi_mars_bigtts", label: "少儿故事" },
  { value: "zh_male_silang_mars_bigtts", label: "四郎" },
  { value: "zh_female_qiaopinvsheng_mars_bigtts", label: "俏皮女声" },
  { value: "zh_male_lanxiaoyang_mars_bigtts", label: "懒音绵宝" },
  { value: "zh_male_dongmanhaimian_mars_bigtts", label: "亮嗓萌仔" },
  { value: "zh_male_jieshuonansheng_mars_bigtts", label: "磁性解说男声/Morgan" },
  { value: "zh_female_jitangmeimei_mars_bigtts", label: "鸡汤妹妹/Hope" },
  { value: "zh_female_tiexinnvsheng_mars_bigtts", label: "贴心女声/Candy" },
  { value: "zh_female_mengyatou_mars_bigtts", label: "萌丫头/Cutey" },

  // 有声阅读
  { value: "ICL_zh_male_neiliancaijun_e991be511569_tob", label: "内敛才俊" },
  { value: "ICL_zh_male_yangyang_v1_tob", label: "温暖少年" },
  { value: "ICL_zh_male_flc_v1_tob", label: "儒雅公子" },
  { value: "zh_male_changtianyi_mars_bigtts", label: "悬疑解说" },
  { value: "zh_male_ruyaqingnian_mars_bigtts", label: "儒雅青年" },
  { value: "zh_male_baqiqingshu_mars_bigtts", label: "霸气青叔" },
  { value: "zh_male_qingcang_mars_bigtts", label: "擎苍" },
  { value: "zh_male_yangguangqingnian_mars_bigtts", label: "活力小哥" },
  { value: "zh_female_gufengshaoyu_mars_bigtts", label: "古风少御" },
  { value: "zh_female_wenroushunv_mars_bigtts", label: "温柔淑女" },
  { value: "zh_male_fanjuanqingnian_mars_bigtts", label: "反卷青年" },
]

export function getProviderLabel(providerId: string): string {
  return PROVIDER_LABELS[providerId] ?? providerId
}
